INSERT INTO restaurant VALUES (0, "Heaven's Barbeque", 0.606, "resto/Heaven's Barbeque.jpg");
INSERT INTO restaurant VALUES (1, "Jonas", 0.745, "resto/Jonas.jpg");
INSERT INTO restaurant VALUES (2, "Brothers Burger", 0.305, "resto/Brothers Burger.gif");
INSERT INTO restaurant VALUES (3, "S&R New York Style Pizza", 0.827, "resto/S&R New York Style Pizza.jpg");
INSERT INTO restaurant VALUES (4, "Max's Restaurant", 0.882, "resto/Max's Restaurant.png'");
INSERT INTO restaurant VALUES (5, "Jollibee", 0.752, "resto/Jollibee.jpg");
INSERT INTO restaurant VALUES (6, "McDonald's", 0.869, "resto/McDonald's.gif");
INSERT INTO restaurant VALUES (7, "Chowking", 0.76, "resto/Chowking.png");
INSERT INTO restaurant VALUES (8, "Burger King", 1.184, "resto/Burger King.png");
INSERT INTO restaurant VALUES (9, "KFC", 0.88, "resto/KFC.png");
INSERT INTO restaurant VALUES (10, "Yellow Cab", 0.24, "resto/Yellow Cab.png");
INSERT INTO food VALUES(0, "Buffalo Wings with Blue Cheese Dip", 0, "225.00", "Buffalo Wings with Blue Cheese Dip.jpg");
INSERT INTO food_tag VALUES (0, "chicken");
INSERT INTO food VALUES(1, "Sausage Platter", 0, "285.00", "Sausage Platter.jpg");
INSERT INTO food_tag VALUES (1, "meat");
INSERT INTO food_tag VALUES (1, "sausage");
INSERT INTO food VALUES(2, "Beef Nachos", 0, "255.00", "Beef Nachos.jpg");
INSERT INTO food_tag VALUES (2, "beef");
INSERT INTO food_tag VALUES (2, "nachos");
INSERT INTO food VALUES(3, "Asian Salad with Chicken Barbeque", 0, "125.00", "Asian Salad with Chicken Barbeque.jpg");
INSERT INTO food_tag VALUES (3, "chicken");
INSERT INTO food_tag VALUES (3, "salad");
INSERT INTO food VALUES(4, "Mango Asparagus Caesar Salad with Chicken Barbeque", 0, "135.00", "Mango Asparagus Caesar Salad with Chicken Barbeque.jpg");
INSERT INTO food_tag VALUES (4, "chicken");
INSERT INTO food_tag VALUES (4, "salad");
INSERT INTO food VALUES(5, "Cheesy Pumpkin Soup", 0, "115.00", "Cheesy Pumpkin Soup.jpg");
INSERT INTO food_tag VALUES (5, "soup");
INSERT INTO food VALUES(6, "Cheesy Broccoli Soup", 0, "125.00", "Cheesy Broccoli Soup.jpg");
INSERT INTO food_tag VALUES (6, "soup");
INSERT INTO food VALUES(7, "Heaven Barsilog", 0, "155.00", "Heaven Barsilog.jpg");
INSERT INTO food_tag VALUES (7, "egg");
INSERT INTO food_tag VALUES (7, "barbeque");
INSERT INTO food_tag VALUES (7, "pork");
INSERT INTO food_tag VALUES (7, "silog");
INSERT INTO food_tag VALUES (7, "rice");
INSERT INTO food VALUES(8, "Sausage Bowl", 0, "155.00", "Sausage Bowl.jpg");
INSERT INTO food_tag VALUES (8, "egg");
INSERT INTO food_tag VALUES (8, "sausage");
INSERT INTO food_tag VALUES (8, "silog");
INSERT INTO food_tag VALUES (8, "rice");
INSERT INTO food VALUES(9, "Chicken Bowl", 0, "165.00", "Chicken Bowl.jpg");
INSERT INTO food_tag VALUES (9, "chicken");
INSERT INTO food_tag VALUES (9, "rice");
INSERT INTO food VALUES(10, "Liempo Bowl", 0, "175.00", "Liempo Bowl.jpg");
INSERT INTO food_tag VALUES (10, "liempo");
INSERT INTO food_tag VALUES (10, "pork");
INSERT INTO food_tag VALUES (10, "silog");
INSERT INTO food_tag VALUES (10, "egg");
INSERT INTO food_tag VALUES (10, "rice");
INSERT INTO food VALUES(11, "Tapsilog Bowl", 0, "145.00", "Tapsilog Bowl.jpg");
INSERT INTO food_tag VALUES (11, "tapa");
INSERT INTO food_tag VALUES (11, "pork");
INSERT INTO food_tag VALUES (11, "egg");
INSERT INTO food_tag VALUES (11, "silog");
INSERT INTO food_tag VALUES (11, "rice");
INSERT INTO food VALUES(12, "Cheese Burger Blast with Egg and Garlic Rice", 0, "155.00", "Cheese Burger Blast with Egg and Garlic Rice.jpg");
INSERT INTO food_tag VALUES (12, "burger");
INSERT INTO food_tag VALUES (12, "egg");
INSERT INTO food_tag VALUES (12, "rice");
INSERT INTO food VALUES(13, "Maple Cured Bacon and Egg with Garlic Rice", 0, "155.00", "Maple Cured Bacon and Egg with Garlic Rice.jpg");
INSERT INTO food_tag VALUES (13, "bacon");
INSERT INTO food_tag VALUES (13, "egg");
INSERT INTO food_tag VALUES (13, "rice");
INSERT INTO food VALUES(14, "Longganisa (Native Sausage) with Egg and Garlic Rice", 0, "135.00", "Longganisa (Native Sausage) with Egg and Garlic Rice.jpg");
INSERT INTO food_tag VALUES (14, "longganisa");
INSERT INTO food_tag VALUES (14, "egg");
INSERT INTO food_tag VALUES (14, "rice");
INSERT INTO food VALUES(15, "Sausage with Egg and Croissant", 0, "175.00", "Sausage with Egg and Croissant.jpg");
INSERT INTO food_tag VALUES (15, "sausage");
INSERT INTO food_tag VALUES (15, "egg");
INSERT INTO food VALUES(16, "Maple Cured Bacon and Egg with Croissant", 0, "175.00", "Maple Cured Bacon and Egg with Croissant.jpg");
INSERT INTO food_tag VALUES (16, "bacon");
INSERT INTO food_tag VALUES (16, "egg");
INSERT INTO food VALUES(17, "Cheeseburger", 0, "95.00", "Cheeseburger.jpg");
INSERT INTO food_tag VALUES (17, "burger");
INSERT INTO food VALUES(18, "Cheesy Hungarian", 0, "125.00", "Cheesy Hungarian.jpg");
INSERT INTO food_tag VALUES (18, "sausage");
INSERT INTO food_tag VALUES (18, "sandwich");
INSERT INTO food VALUES(19, "Beef Mushroom", 0, "155.00", "Beef Mushroom.jpg");
INSERT INTO food_tag VALUES (19, "soup");
INSERT INTO food_tag VALUES (19, "beef");
INSERT INTO food VALUES(20, "TINAPAsta in Pesto Sauce", 0, "125.00", "TINAPAsta in Pesto Sauce.jpg");
INSERT INTO food_tag VALUES (20, "pasta");
INSERT INTO food_tag VALUES (20, "fish");
INSERT INTO food VALUES(21, "Spaghetti Alla Arrabiata", 0, "99.00", "Spaghetti Alla Arrabiata.jpg");
INSERT INTO food_tag VALUES (21, "pasta");
INSERT INTO food VALUES(22, "Meatballs on Italian Herb Sauce", 0, "125.00", "Meatballs on Italian Herb Sauce.jpg");
INSERT INTO food_tag VALUES (22, "pasta");
INSERT INTO food VALUES(23, "Puttanesca", 0, "115.00", "Puttanesca.jpg");
INSERT INTO food_tag VALUES (23, "pasta");
INSERT INTO food VALUES(24, "Creamy Mushroom and Bacon Carbonara", 0, "115.00", "Creamy Mushroom and Bacon Carbonara.jpg");
INSERT INTO food_tag VALUES (24, "pasta");
INSERT INTO food VALUES(25, "One-half Chicken", 0, "275.00", "One-half Chicken.jpg");
INSERT INTO food_tag VALUES (25, "chicken");
INSERT INTO food VALUES(26, "Pork Belly Whole Slab", 0, "265.00", "Pork Belly Whole Slab.jpg");
INSERT INTO food_tag VALUES (26, "pork");
INSERT INTO food VALUES(27, "Angus Rib Eye with Crispy Potato Wedges", 0, "625.00", "Angus Rib Eye with Crispy Potato Wedges.jpg");
INSERT INTO food_tag VALUES (27, "beef");
INSERT INTO food VALUES(28, "Grilled Fish in Lemon Butter Sauce", 0, "285.00", "Grilled Fish in Lemon Butter Sauce.jpg");
INSERT INTO food_tag VALUES (28, "fish");
INSERT INTO food VALUES(29, "Sausage Breakfast", 1, "235.00", "Sausage Breakfast.jpg");
INSERT INTO food_tag VALUES (29, "sausage");
INSERT INTO food_tag VALUES (29, "breakfast");
INSERT INTO food VALUES(30, "Corned Beef Breakfast", 1, "195.00", "Corned Beef Breakfast.jpg");
INSERT INTO food_tag VALUES (30, "beef");
INSERT INTO food_tag VALUES (30, "breakfast");
INSERT INTO food VALUES(31, "Beef Tapa Breakfast", 1, "215.00", "Beef Tapa Breakfast.jpg");
INSERT INTO food_tag VALUES (31, "beef");
INSERT INTO food_tag VALUES (31, "breakfast");
INSERT INTO food VALUES(32, "Country Style Breakfast", 1, "215.00", "Country Style Breakfast.jpg");
INSERT INTO food_tag VALUES (32, "breakfast");
INSERT INTO food VALUES(33, "Garden Salad with Roasted Walnuts", 1, "178.00", "Garden Salad with Roasted Walnuts.jpg");
INSERT INTO food_tag VALUES (33, "salad");
INSERT INTO food VALUES(34, "Kani with Citrus Salad", 1, "178.00", "Kani with Citrus Salad.jpg");
INSERT INTO food_tag VALUES (34, "salad");
INSERT INTO food_tag VALUES (34, "kani");
INSERT INTO food VALUES(35, "Caesar Salad with Chicken", 1, "188.00", "Caesar Salad with Chicken.jpg");
INSERT INTO food_tag VALUES (35, "salad");
INSERT INTO food_tag VALUES (35, "chicken");
INSERT INTO food VALUES(36, "Kani Salad Sandwich", 1, "165.00", "Kani Salad Sandwich.jpg");
INSERT INTO food_tag VALUES (36, "salad");
INSERT INTO food_tag VALUES (36, "kani");
INSERT INTO food VALUES(37, "Ham and Cheese Sandwich", 1, "165.00", "Ham and Cheese Sandwich.jpg");
INSERT INTO food_tag VALUES (37, "sandwich");
INSERT INTO food_tag VALUES (37, "ham");
INSERT INTO food VALUES(38, "Chicken Salad Sandwich", 1, "165.00", "Chicken Salad Sandwich.jpg");
INSERT INTO food_tag VALUES (38, "sandwich");
INSERT INTO food_tag VALUES (38, "chicken");
INSERT INTO food VALUES(39, "Fish Fillet with Tofu and Fresh Leeks", 1, "165.00", "Fish Fillet with Tofu and Fresh Leeks.jpg");
INSERT INTO food_tag VALUES (39, "fish");
INSERT INTO food VALUES(40, "Original JONAS Pares", 1, "198.00", "Original JONAS Pares.jpg");
INSERT INTO food_tag VALUES (40, "pares");
INSERT INTO food_tag VALUES (40, "soup");
INSERT INTO food VALUES(41, "Chicken with Black Beans", 1, "195.00", "Chicken with Black Beans.jpg");
INSERT INTO food_tag VALUES (41, "chicken");
INSERT INTO food VALUES(42, "Spaghetti and Meatballs", 1, "165.00", "Spaghetti and Meatballs.jpg");
INSERT INTO food_tag VALUES (42, "pasta");
INSERT INTO food VALUES(43, "Salmon Fillet with Soy and Sesame", 1, "285.00", "Salmon Fillet with Soy and Sesame.jpg");
INSERT INTO food_tag VALUES (43, "fish");
INSERT INTO food VALUES(44, "Pork Ribs Salt and Pepper", 1, "195.00", "Pork Ribs Salt and Pepper.jpg");
INSERT INTO food_tag VALUES (44, "pork");
INSERT INTO food VALUES(45, "Prawn Tempura", 1, "248.00", "Prawn Tempura.jpg");
INSERT INTO food_tag VALUES (45, "shrimp");
INSERT INTO food VALUES(46, "Chicken Wings Salt and Pepper", 1, "245.00", "Chicken Wings Salt and Pepper.jpg");
INSERT INTO food_tag VALUES (46, "chicken");
INSERT INTO food VALUES(47, "Chicken with Salted Egg Yolk", 1, "245.00", "Chicken with Salted Egg Yolk.jpg");
INSERT INTO food_tag VALUES (47, "chicken");
INSERT INTO food VALUES(48, "Sweet and Sour Fish", 1, "238.00", "Sweet and Sour Fish.jpg");
INSERT INTO food_tag VALUES (48, "fish");
INSERT INTO food VALUES(49, "Lechon Paksiw", 1, "245.00", "Lechon Paksiw.jpg");
INSERT INTO food_tag VALUES (49, "pork");
INSERT INTO food VALUES(50, "Mixed Vegetables", 1, "149.00", "Mixed Vegetables.jpg");
INSERT INTO food_tag VALUES (50, "vegetables");
INSERT INTO food VALUES(51, "Wonton Noodle", 1, "185.00", "Wonton Noodle.jpg");
INSERT INTO food_tag VALUES (51, "noodle");
INSERT INTO food VALUES(52, "Beef Noodle", 1, "195.00", "Beef Noodle.jpg");
INSERT INTO food_tag VALUES (52, "beef");
INSERT INTO food_tag VALUES (52, "noodle");
INSERT INTO food VALUES(53, "Chicken Noodle", 1, "175.00", "Chicken Noodle.jpg");
INSERT INTO food_tag VALUES (53, "chicken");
INSERT INTO food_tag VALUES (53, "noodle");
INSERT INTO food VALUES(54, "Seafood Noodle", 1, "210.00", "Seafood Noodle.jpg");
INSERT INTO food_tag VALUES (54, "seafood");
INSERT INTO food_tag VALUES (54, "noodle");
INSERT INTO food VALUES(55, "A Bit of Everything Noodle", 1, "225.00", "A Bit of Everything Noodle.jpg");
INSERT INTO food_tag VALUES (55, "chicken");
INSERT INTO food_tag VALUES (55, "beef");
INSERT INTO food_tag VALUES (55, "seafood");
INSERT INTO food_tag VALUES (55, "noodle");
INSERT INTO food VALUES(56, "Asadio Siopao", 1, "45.00", "Asadio Siopao.jpg");
INSERT INTO food_tag VALUES (56, "pork");
INSERT INTO food VALUES(57, "Bola-bola Siopai", 1, "45.00", "Bola-bola Siopai.jpg");
INSERT INTO food_tag VALUES (57, "pork");
INSERT INTO food VALUES(58, "Jumbo Siopao", 1, "45.00", "Jumbo Siopao.jpg");
INSERT INTO food_tag VALUES (58, "pork");
INSERT INTO food VALUES(59, "Spring Rolls", 1, "88.00", "Spring Rolls.jpg");
INSERT INTO food_tag VALUES (59, "vegetables");
INSERT INTO food VALUES(60, "Bros Burger Meal", 2, "270.00", "Bros Burger Meal.jpg");
INSERT INTO food_tag VALUES (60, "beef");
INSERT INTO food_tag VALUES (60, "burger");
INSERT INTO food VALUES(61, "Big Brothers Meal", 2, "315.00", "Big Brothers Meal.jpg");
INSERT INTO food_tag VALUES (61, "beef");
INSERT INTO food_tag VALUES (61, "burger");
INSERT INTO food VALUES(62, "Lamb Burger Meal", 2, "395.00", "Lamb Burger Meal.jpg");
INSERT INTO food_tag VALUES (62, "lamb");
INSERT INTO food_tag VALUES (62, "burger");
INSERT INTO food VALUES(63, "Angus Burger Meal", 2, "395.00", "Angus Burger Meal.jpg");
INSERT INTO food_tag VALUES (63, "beef");
INSERT INTO food_tag VALUES (63, "burger");
INSERT INTO food VALUES(64, "Pounder Meal", 2, "395.00", "Pounder Meal.jpg");
INSERT INTO food_tag VALUES (64, "beef");
INSERT INTO food_tag VALUES (64, "burger");
INSERT INTO food VALUES(65, "Double Brothers Burger", 2, "215.00", "Double Brothers Burger.jpg");
INSERT INTO food_tag VALUES (65, "beef");
INSERT INTO food_tag VALUES (65, "burger");
INSERT INTO food VALUES(66, "Blues Brother Burger Meal", 2, "295.00", "Blues Brother Burger Meal.jpg");
INSERT INTO food_tag VALUES (66, "beef");
INSERT INTO food_tag VALUES (66, "burger");
INSERT INTO food VALUES(67, "Ranchero Burger Meal", 2, "295.00", "Ranchero Burger Meal.jpg");
INSERT INTO food_tag VALUES (67, "beef");
INSERT INTO food_tag VALUES (67, "burger");
INSERT INTO food VALUES(68, "Extreme Bacon Burger Meal", 2, "295.00", "Extreme Bacon Burger Meal.jpg");
INSERT INTO food_tag VALUES (68, "pork");
INSERT INTO food_tag VALUES (68, "burger");
INSERT INTO food_tag VALUES (68, "beef");
INSERT INTO food VALUES(69, "Manileno Sandwich", 2, "235.00", "Manileno Sandwich.jpg");
INSERT INTO food_tag VALUES (69, "sandwich");
INSERT INTO food VALUES(70, "Cheese Steak Sandwich", 2, "235.00", "Cheese Steak Sandwich.jpg");
INSERT INTO food_tag VALUES (70, "sandwich");
INSERT INTO food VALUES(71, "Grilled Chicken Sandwich", 2, "235.00", "Grilled Chicken Sandwich.jpg");
INSERT INTO food_tag VALUES (71, "chicken");
INSERT INTO food_tag VALUES (71, "sandwich");
INSERT INTO food VALUES(72, "Crispy Fish Sandwich", 2, "235.00", "Crispy Fish Sandwich.jpg");
INSERT INTO food_tag VALUES (72, "fish");
INSERT INTO food_tag VALUES (72, "sandwich");
INSERT INTO food VALUES(73, "Chorizo Sandwich", 2, "235.00", "Chorizo Sandwich.jpg");
INSERT INTO food_tag VALUES (73, "sandwich");
INSERT INTO food VALUES(74, "Chicken Zumo", 2, "235.00", "Chicken Zumo.jpg");
INSERT INTO food_tag VALUES (74, "chicken");
INSERT INTO food_tag VALUES (74, "sandwich");
INSERT INTO food VALUES(75, "Bacon Mac and Cheese", 2, "195.00", "Bacon Mac and Cheese.jpg");
INSERT INTO food_tag VALUES (75, "pork");
INSERT INTO food_tag VALUES (75, "pasta");
INSERT INTO food VALUES(76, "Pasta Amatriciana", 2, "195.00", "Pasta Amatriciana.jpg");
INSERT INTO food_tag VALUES (76, "pasta");
INSERT INTO food VALUES(77, "Cheese Pizza", 3, "569.00", "Cheese Pizza.jpg");
INSERT INTO food_tag VALUES (77, "pizza");
INSERT INTO food VALUES(78, "Pepperoni Pizza", 3, "629.00", "Pepperoni Pizza.jpg");
INSERT INTO food_tag VALUES (78, "pizza");
INSERT INTO food_tag VALUES (78, "pork");
INSERT INTO food VALUES(79, "Garlic Shrimp Pizza", 3, "629.00", "Garlic Shrimp Pizza.jpg");
INSERT INTO food_tag VALUES (79, "pizza");
INSERT INTO food_tag VALUES (79, "shrimp");
INSERT INTO food VALUES(80, "Cheeseburger", 3, "119.00", "Cheeseburger.jpg");
INSERT INTO food_tag VALUES (80, "beef");
INSERT INTO food_tag VALUES (80, "burger");
INSERT INTO food VALUES(81, "Chicken Caesar Salad", 3, "179.00", "Chicken Caesar Salad.jpg");
INSERT INTO food_tag VALUES (81, "chicken");
INSERT INTO food_tag VALUES (81, "salad");
INSERT INTO food VALUES(82, "1pc Chicken", 3, "99.00", "1pc Chicken.jpg");
INSERT INTO food_tag VALUES (82, "chicken");
INSERT INTO food_tag VALUES (82, "rice");
INSERT INTO food VALUES(83, "Chicken Dinner Meal", 4, "332.20", "Chicken Dinner Meal.jpg");
INSERT INTO food_tag VALUES (83, "chicken");
INSERT INTO food_tag VALUES (83, "rice");
INSERT INTO food VALUES(84, "Spring Chicken Meal", 4, "299.20", "Spring Chicken Meal.jpg");
INSERT INTO food_tag VALUES (84, "chicken");
INSERT INTO food_tag VALUES (84, "rice");
INSERT INTO food VALUES(85, "Chopsuey Meal", 4, "282.70", "Chopsuey Meal.jpg");
INSERT INTO food_tag VALUES (85, "vegetables");
INSERT INTO food_tag VALUES (85, "rice");
INSERT INTO food VALUES(86, "Platter Meal", 4, "282.70", "Platter Meal.jpg");
INSERT INTO food_tag VALUES (86, "chicken");
INSERT INTO food_tag VALUES (86, "rice");
INSERT INTO food VALUES(87, "Fiesta Plate Meal", 4, "275.00", "Fiesta Plate Meal.jpg");
INSERT INTO food_tag VALUES (87, "rice");
INSERT INTO food_tag VALUES (87, "chicken");
INSERT INTO food VALUES(88, "Chicken Barbecue Meal", 4, "247.50", "Chicken Barbecue Meal.jpg");
INSERT INTO food_tag VALUES (88, "rice");
INSERT INTO food_tag VALUES (88, "chicken");
INSERT INTO food VALUES(89, "Budget Meal", 4, "242.00", "Budget Meal.jpg");
INSERT INTO food_tag VALUES (89, "rice");
INSERT INTO food_tag VALUES (89, "chicken");
INSERT INTO food VALUES(90, "Basic Meal", 4, "209.00", "Basic Meal.jpg");
INSERT INTO food_tag VALUES (90, "rice");
INSERT INTO food_tag VALUES (90, "chicken");
INSERT INTO food VALUES(91, "2-pc. Pancake Meal", 5, "60.50", "2-pc. Pancake Meal.jpg");
INSERT INTO food_tag VALUES (91, "breakfast");
INSERT INTO food VALUES(92, "Pancake with Longganisa Meal", 5, "99.00", "Pancake with Longganisa Meal.jpg");
INSERT INTO food_tag VALUES (92, "breakfast");
INSERT INTO food_tag VALUES (92, "longganisa");
INSERT INTO food_tag VALUES (92, "pork");
INSERT INTO food VALUES(93, "Hotdog Meal", 5, "75.90", "Hotdog Meal.jpg");
INSERT INTO food_tag VALUES (93, "breakfast");
INSERT INTO food_tag VALUES (93, "egg");
INSERT INTO food_tag VALUES (93, "hotdog");
INSERT INTO food_tag VALUES (93, "pork");
INSERT INTO food_tag VALUES (93, "rice");
INSERT INTO food VALUES(94, "Beef Tapa Meal", 5, "108.90", "Beef Tapa Meal.jpg");
INSERT INTO food_tag VALUES (94, "breakfast");
INSERT INTO food_tag VALUES (94, "egg");
INSERT INTO food_tag VALUES (94, "rice");
INSERT INTO food VALUES(95, "Breakfast Steak Meal", 5, "75.90", "Breakfast Steak Meal.jpg");
INSERT INTO food_tag VALUES (95, "breakfast");
INSERT INTO food_tag VALUES (95, "egg");
INSERT INTO food_tag VALUES (95, "rice");
INSERT INTO food VALUES(96, "Longganisa Meal", 5, "108.90", "Longganisa Meal.jpg");
INSERT INTO food_tag VALUES (96, "breakfast");
INSERT INTO food_tag VALUES (96, "egg");
INSERT INTO food_tag VALUES (96, "rice");
INSERT INTO food VALUES(97, "1-pc. Chickenjoy Meal", 5, "82.00", "1-pc. Chickenjoy Meal.jpg");
INSERT INTO food_tag VALUES (97, "chicken");
INSERT INTO food_tag VALUES (97, "rice");
INSERT INTO food VALUES(98, "2-pc. Chickenjoy Meal", 5, "150.00", "2-pc. Chickenjoy Meal.jpg");
INSERT INTO food_tag VALUES (98, "chicken");
INSERT INTO food_tag VALUES (98, "rice");
INSERT INTO food VALUES(99, "1-pc. Chickenjoy with Spaghetti", 5, "115.00", "1-pc. Chickenjoy with Spaghetti.jpg");
INSERT INTO food_tag VALUES (99, "chicken");
INSERT INTO food_tag VALUES (99, "pasta");
INSERT INTO food VALUES(100, "Jolly Spaghetti", 5, "55.00", "Jolly Spaghetti.jpg");
INSERT INTO food_tag VALUES (100, "pasta");
INSERT INTO food VALUES(101, "Jolly Spagetti with Burger Steak", 5, "99.00", "Jolly Spagetti with Burger Steak.jpg");
INSERT INTO food_tag VALUES (101, "pork");
INSERT INTO food_tag VALUES (101, "pasta");
INSERT INTO food VALUES(102, "Cheesy Classic Hotdog", 5, "90.00", "Cheesy Classic Hotdog.jpg");
INSERT INTO food_tag VALUES (102, "pork");
INSERT INTO food VALUES(103, "Chili Cheese Hotdog", 5, "99.00", "Chili Cheese Hotdog.jpg");
INSERT INTO food_tag VALUES (103, "pork");
INSERT INTO food VALUES(104, "Yum Burger Meal", 5, "75.00", "Yum Burger Meal.jpg");
INSERT INTO food_tag VALUES (104, "beef");
INSERT INTO food_tag VALUES (104, "burger");
INSERT INTO food VALUES(105, "Yum Cheeseburger Meal", 5, "85.00", "Yum Cheeseburger Meal.jpg");
INSERT INTO food_tag VALUES (105, "beef");
INSERT INTO food_tag VALUES (105, "burger");
INSERT INTO food VALUES(106, "Yum with TLC", 5, "102.00", "Yum with TLC.jpg");
INSERT INTO food_tag VALUES (106, "beef");
INSERT INTO food_tag VALUES (106, "burger");
INSERT INTO food VALUES(107, "Champ", 5, "165.00", "Champ.jpg");
INSERT INTO food_tag VALUES (107, "beef");
INSERT INTO food_tag VALUES (107, "burger");
INSERT INTO food VALUES(108, "Cheesy Bacon Mushroom Yum", 5, "103.00", "Cheesy Bacon Mushroom Yum.jpg");
INSERT INTO food_tag VALUES (108, "beef");
INSERT INTO food_tag VALUES (108, "burger");
INSERT INTO food VALUES(109, "Cheesy Bacon Mushroom Champ", 5, "175.00", "Cheesy Bacon Mushroom Champ.jpg");
INSERT INTO food_tag VALUES (109, "beef");
INSERT INTO food_tag VALUES (109, "burger");
INSERT INTO food VALUES(110, "Mushroom Gravy Burger Steak", 5, "55.00", "Mushroom Gravy Burger Steak.jpg");
INSERT INTO food_tag VALUES (110, "beef");
INSERT INTO food_tag VALUES (110, "burger");
INSERT INTO food_tag VALUES (110, "rice");
INSERT INTO food VALUES(111, "Pepper Cream Burger Steak", 5, "55.00", "Pepper Cream Burger Steak.jpg");
INSERT INTO food_tag VALUES (111, "beef");
INSERT INTO food_tag VALUES (111, "burger");
INSERT INTO food_tag VALUES (111, "rice");
INSERT INTO food VALUES(112, "Big Burger Steak", 5, "110.00", "Big Burger Steak.jpg");
INSERT INTO food_tag VALUES (112, "beef");
INSERT INTO food_tag VALUES (112, "burger");
INSERT INTO food_tag VALUES (112, "rice");
INSERT INTO food VALUES(113, "Big Mac Value Meal", 6, "188.00", "Big Mac Value Meal.jpg");
INSERT INTO food_tag VALUES (113, "beef");
INSERT INTO food_tag VALUES (113, "burger");
INSERT INTO food VALUES(114, "Quarter Pounder with Cheese", 6, "187.00", "Quarter Pounder with Cheese.jpg");
INSERT INTO food_tag VALUES (114, "beef");
INSERT INTO food_tag VALUES (114, "burger");
INSERT INTO food VALUES(115, "McDouble Deluxe", 6, "166.00", "McDouble Deluxe.jpg");
INSERT INTO food_tag VALUES (115, "beef");
INSERT INTO food_tag VALUES (115, "burger");
INSERT INTO food VALUES(116, "Double Cheeseburger", 6, "157.00", "Double Cheeseburger.jpg");
INSERT INTO food_tag VALUES (116, "beef");
INSERT INTO food_tag VALUES (116, "burger");
INSERT INTO food VALUES(117, "McChicken Sandwich", 6, "155.00", "McChicken Sandwich.jpg");
INSERT INTO food_tag VALUES (117, "chicken");
INSERT INTO food_tag VALUES (117, "burger");
INSERT INTO food VALUES(118, "Filet-O-Fish", 6, "155.00", "Filet-O-Fish.jpg");
INSERT INTO food_tag VALUES (118, "fish");
INSERT INTO food_tag VALUES (118, "burger");
INSERT INTO food VALUES(119, "Cheeseburger Deluxe", 6, "130.00", "Cheeseburger Deluxe.jpg");
INSERT INTO food_tag VALUES (119, "beef");
INSERT INTO food_tag VALUES (119, "burger");
INSERT INTO food VALUES(120, "Cheeseburger", 6, "109.00", "Cheeseburger.jpg");
INSERT INTO food_tag VALUES (120, "beef");
INSERT INTO food_tag VALUES (120, "burger");
INSERT INTO food VALUES(121, "Burger McDo", 6, "99.00", "Burger McDo.jpg");
INSERT INTO food_tag VALUES (121, "beef");
INSERT INTO food_tag VALUES (121, "burger");
INSERT INTO food VALUES(122, "2-pc Chicken McDo with Rice", 6, "164.00", "2-pc Chicken McDo with Rice.jpg");
INSERT INTO food_tag VALUES (122, "chicken");
INSERT INTO food_tag VALUES (122, "rice");
INSERT INTO food VALUES(123, "1-pc Chicken McDo with Rice", 6, "98.00", "1-pc Chicken McDo with Rice.jpg");
INSERT INTO food_tag VALUES (123, "chicken");
INSERT INTO food_tag VALUES (123, "rice");
INSERT INTO food VALUES(124, "1-pc Chicken McDo and McSpaghetti", 6, "124.00", "1-pc Chicken McDo and McSpaghetti.jpg");
INSERT INTO food_tag VALUES (124, "chicken");
INSERT INTO food_tag VALUES (124, "pasta");
INSERT INTO food VALUES(125, "Pork Chao Fan", 7, "59.00", "Pork Chao Fan.jpg");
INSERT INTO food_tag VALUES (125, "pork");
INSERT INTO food_tag VALUES (125, "rice");
INSERT INTO food VALUES(126, "Beef Chao Fan", 7, "67.00", "Beef Chao Fan.jpg");
INSERT INTO food_tag VALUES (126, "beef");
INSERT INTO food_tag VALUES (126, "rice");
INSERT INTO food VALUES(127, "Yangchow", 7, "77.00", "Yangchow.jpg");
INSERT INTO food_tag VALUES (127, "pork");
INSERT INTO food_tag VALUES (127, "rice");
INSERT INTO food VALUES(128, "1-pc Chinese-Style Fried Chicken", 7, "87.00", "1-pc Chinese-Style Fried Chicken.jpg");
INSERT INTO food_tag VALUES (128, "chicken");
INSERT INTO food_tag VALUES (128, "rice");
INSERT INTO food VALUES(129, "2-pc Chinese-Style Fried Chicken", 7, "148.00", "2-pc Chinese-Style Fried Chicken.jpg");
INSERT INTO food_tag VALUES (129, "chicken");
INSERT INTO food_tag VALUES (129, "rice");
INSERT INTO food VALUES(130, "Chinese-Style Porkchop", 7, "105.00", "Chinese-Style Porkchop.jpg");
INSERT INTO food_tag VALUES (130, "pork");
INSERT INTO food_tag VALUES (130, "rice");
INSERT INTO food VALUES(131, "Sweet and Sour Pork", 7, "105.00", "Sweet and Sour Pork.jpg");
INSERT INTO food_tag VALUES (131, "pork");
INSERT INTO food_tag VALUES (131, "rice");
INSERT INTO food VALUES(132, "Sweet and Sour Fish", 7, "105.00", "Sweet and Sour Fish.jpg");
INSERT INTO food_tag VALUES (132, "fish");
INSERT INTO food_tag VALUES (132, "rice");
INSERT INTO food VALUES(133, "Whopper Jr. Meal", 8, "119.00", "Whopper Jr. Meal.jpg");
INSERT INTO food_tag VALUES (133, "beef");
INSERT INTO food_tag VALUES (133, "burger");
INSERT INTO food VALUES(134, "Whopper Meal", 8, "179.00", "Whopper Meal.jpg");
INSERT INTO food_tag VALUES (134, "beef");
INSERT INTO food_tag VALUES (134, "burger");
INSERT INTO food VALUES(135, "4 Cheese Whopper", 8, "219.00", "4 Cheese Whopper.jpg");
INSERT INTO food_tag VALUES (135, "beef");
INSERT INTO food_tag VALUES (135, "burger");
INSERT INTO food VALUES(136, "3 Meat Whopper", 8, "219.00", "3 Meat Whopper.jpg");
INSERT INTO food_tag VALUES (136, "beef");
INSERT INTO food_tag VALUES (136, "burger");
INSERT INTO food VALUES(137, "Double Cheeseburger", 8, "179.00", "Double Cheeseburger.jpg");
INSERT INTO food_tag VALUES (137, "beef");
INSERT INTO food_tag VALUES (137, "burger");
INSERT INTO food VALUES(138, "Double BBQ Bacon Cheese", 8, "215.00", "Double BBQ Bacon Cheese.jpg");
INSERT INTO food_tag VALUES (138, "beef");
INSERT INTO food_tag VALUES (138, "burger");
INSERT INTO food VALUES(139, "Double Mushroom Swiss", 8, "215.00", "Double Mushroom Swiss.jpg");
INSERT INTO food_tag VALUES (139, "beef");
INSERT INTO food_tag VALUES (139, "burger");
INSERT INTO food VALUES(140, "Classis Angus Steakhouse", 8, "219.00", "Classis Angus Steakhouse.jpg");
INSERT INTO food_tag VALUES (140, "beef");
INSERT INTO food_tag VALUES (140, "burger");
INSERT INTO food VALUES(141, "X-tra Long Chicken", 8, "170.00", "X-tra Long Chicken.jpg");
INSERT INTO food_tag VALUES (141, "chicken");
INSERT INTO food_tag VALUES (141, "sandwich");
INSERT INTO food VALUES(142, "Chicken Nugget Burger", 8, "119.00", "Chicken Nugget Burger.jpg");
INSERT INTO food_tag VALUES (142, "chicken");
INSERT INTO food_tag VALUES (142, "burger");
INSERT INTO food VALUES(143, "2-pc King's Crunchy Chicken", 8, "179.00", "2-pc King's Crunchy Chicken.jpg");
INSERT INTO food_tag VALUES (143, "chicken");
INSERT INTO food_tag VALUES (143, "rice");
INSERT INTO food VALUES(144, "1-pc King's Crunchy Chicken", 8, "119.00", "1-pc King's Crunchy Chicken.jpg");
INSERT INTO food_tag VALUES (144, "chicken");
INSERT INTO food_tag VALUES (144, "rice");
INSERT INTO food VALUES(145, "1-pc Chicken Spaghetti", 9, "99.00", "1-pc Chicken Spaghetti.jpg");
INSERT INTO food_tag VALUES (145, "chicken");
INSERT INTO food_tag VALUES (145, "pasta");
INSERT INTO food VALUES(146, "1-pc Chicken Rice Soup", 9, "99.00", "1-pc Chicken Rice Soup.jpg");
INSERT INTO food_tag VALUES (146, "chicken");
INSERT INTO food_tag VALUES (146, "rice");
INSERT INTO food VALUES(147, "2-pc Chicken with Rice", 9, "120.00", "2-pc Chicken with Rice.jpg");
INSERT INTO food_tag VALUES (147, "chicken");
INSERT INTO food_tag VALUES (147, "rice");
INSERT INTO food VALUES(148, "1-pc Classic Fully Loaded Meal", 9, "160.00", "1-pc Classic Fully Loaded Meal.jpg");
INSERT INTO food_tag VALUES (148, "chicken");
INSERT INTO food_tag VALUES (148, "rice");
INSERT INTO food VALUES(149, "2-pc Classic Fully Loaded Meal", 9, "190.00", "2-pc Classic Fully Loaded Meal.jpg");
INSERT INTO food_tag VALUES (149, "chicken");
INSERT INTO food_tag VALUES (149, "rice");
INSERT INTO food VALUES(150, "Chicken Burger", 9, "70.00", "Chicken Burger.jpg");
INSERT INTO food_tag VALUES (150, "chicken");
INSERT INTO food_tag VALUES (150, "burger");
INSERT INTO food VALUES(151, "Twister", 9, "120.00", "Twister.jpg");
INSERT INTO food_tag VALUES (151, "chicken");
INSERT INTO food_tag VALUES (151, "sandwich");
INSERT INTO food VALUES(152, "Zinger", 9, "120.00", "Zinger.jpg");
INSERT INTO food_tag VALUES (152, "chicken");
INSERT INTO food_tag VALUES (152, "sandwich");
INSERT INTO food VALUES(153, "Spaghetti", 9, "50.00", "Spaghetti.jpg");
INSERT INTO food_tag VALUES (153, "pasta");
INSERT INTO food VALUES(154, "Famous Bowl", 9, "65.00", "Famous Bowl.jpg");
INSERT INTO food_tag VALUES (154, "chicken");
INSERT INTO food_tag VALUES (154, "rice");
INSERT INTO food VALUES(155, "Italian Ala King", 9, "116.00", "Italian Ala King.jpg");
INSERT INTO food_tag VALUES (155, "chicken");
INSERT INTO food_tag VALUES (155, "rice");
INSERT INTO food VALUES(156, "Tokyo Pepper Steak", 9, "116.00", "Tokyo Pepper Steak.jpg");
INSERT INTO food_tag VALUES (156, "chicken");
INSERT INTO food_tag VALUES (156, "rice");
INSERT INTO food VALUES(157, "Osaska Teriyaki", 9, "116.00", "Osaska Teriyaki.jpg");
INSERT INTO food_tag VALUES (157, "chicken");
INSERT INTO food_tag VALUES (157, "rice");
INSERT INTO food VALUES(158, "Flavor Shots", 9, "60.00", "Flavor Shots.jpg");
INSERT INTO food_tag VALUES (158, "chicken");
INSERT INTO food_tag VALUES (158, "rice");
INSERT INTO food VALUES(159, "New York's Finest", 10, "400.00", "New York's Finest.jpg");
INSERT INTO food_tag VALUES (159, "pizza");
INSERT INTO food VALUES(160, "Manhattan Meatlovers", 10, "400.00", "Manhattan Meatlovers.jpg");
INSERT INTO food_tag VALUES (160, "pizza");
INSERT INTO food VALUES(161, "Hawaiian", 10, "335.00", "Hawaiian.jpg");
INSERT INTO food_tag VALUES (161, "pizza");
INSERT INTO food VALUES(162, "Four Seasons", 10, "395.00", "Four Seasons.jpg");
INSERT INTO food_tag VALUES (162, "pizza");
INSERT INTO food VALUES(163, "#4 Cheese", 10, "340.00", "#4 Cheese.jpg");
INSERT INTO food_tag VALUES (163, "pizza");
INSERT INTO food VALUES(164, "NY Classic", 10, "340.00", "NY Classic.jpg");
INSERT INTO food_tag VALUES (164, "pizza");
INSERT INTO food VALUES(165, "Barbecue Chicken", 10, "365.00", "Barbecue Chicken.jpg");
INSERT INTO food_tag VALUES (165, "pizza");
INSERT INTO food VALUES(166, "Garden Special", 10, "330.00", "Garden Special.jpg");
INSERT INTO food_tag VALUES (166, "pizza");
INSERT INTO food VALUES(167, "Pepperoni and Mushroom", 10, "330.00", "Pepperoni and Mushroom.jpg");
INSERT INTO food_tag VALUES (167, "pizza");
INSERT INTO food VALUES(168, "Roasted Garlic and Shrimp", 10, "395.00", "Roasted Garlic and Shrimp.jpg");
INSERT INTO food_tag VALUES (168, "pizza");
INSERT INTO food VALUES(169, "Dear Darla", 10, "330.00", "Dear Darla.jpg");
INSERT INTO food_tag VALUES (169, "pizza");
INSERT INTO food VALUES(170, "Four Cheese and Tomatoes", 10, "260.00", "Four Cheese and Tomatoes.jpg");
INSERT INTO food_tag VALUES (170, "pizza");
INSERT INTO food VALUES(171, "Jalapeno and Pepperoni", 10, "260.00", "Jalapeno and Pepperoni.jpg");
INSERT INTO food_tag VALUES (171, "pizza");
INSERT INTO food VALUES(172, "Chelsea's Artichoke Pizza", 10, "280.00", "Chelsea's Artichoke Pizza.jpg");
INSERT INTO food_tag VALUES (172, "pizza");
INSERT INTO food VALUES(173, "Prosciutto Ham and Boursin Cheese", 10, "280.00", "Prosciutto Ham and Boursin Cheese.jpg");
INSERT INTO food_tag VALUES (173, "pizza");
INSERT INTO food VALUES(174, "Salmon with Dill", 10, "280.00", "Salmon with Dill.jpg");
INSERT INTO food_tag VALUES (174, "pizza");
INSERT INTO food VALUES(175, "Charlie Chan Chicken Pasta", 10, "165.00", "Charlie Chan Chicken Pasta.jpg");
INSERT INTO food_tag VALUES (175, "chicken");
INSERT INTO food_tag VALUES (175, "pasta");
INSERT INTO food VALUES(176, "Spaghetti and Meatballs", 10, "170.00", "Spaghetti and Meatballs.jpg");
INSERT INTO food_tag VALUES (176, "pasta");
